apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-uwxxtroy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-uwxxtroy 
  name: go-uwxxtroy
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-uwxxtroy
    weight: 100 
